### ISSUE TITLE
Could not find a declaration file for module 'nanoclamp'.

### ISSUE THREAD

**Issue by rafiandria23** [microlinkhq/nanoclamp#14]
I `nanoclamp` with `TypeScript` and got this error:

`<project_directory>/node_modules/nanoclamp/dist/nanoclamp.js' implicitly has an 'any' type.   Try npm install @types/nanoclamp if it exists or add a new declaration (.d.ts) file containing declare module 'nanoclamp'`

The module works smoothly, but I can't get rid of this error in my code editor.

When I checked the `node_modules` folder, I found that `index.d.ts` doesn't exist even there's no `typings` folder.

**Comment by Kikobeats** [comment]
Thanks for reporting!

Looks like TypeScript types weren't present into the npm bundle:
https://github.com/microlinkhq/nanoclamp/commit/870d35d5f36944ba51a039925f7157d5f09ab82e

It's fixed at `nanoclamp@1.3.4`.

Can you confirm it's working fine for you?

**Comment by rafiandria23** [comment]
@Kikobeats Yes, it's working fine now, thanks for the quick response!
