### ISSUE TITLE
Dynamic text value doesn't update

### ISSUE THREAD

**Issue by derochedesign** [microlinkhq/nanoclamp#19]
I have my text value rotating on a timer (every three seconds or so) and the displayed text stays the same as the first rendered. Interestingly the title attribute does update with the new text value (so I know my end's working) but the displayed text stays static.

**Comment by Kikobeats** [comment]
Can you write a codepen.io reproducing the issue?

**Comment by Kikobeats** [comment]
Released https://github.com/microlinkhq/nanoclamp/releases/tag/v2.0.0 🙂
